name: Run Gradle on PRs
on:
    pull_request:
    push:
        branches: main
jobs:
    prBranch:
        timeout-minutes: 300
        strategy:
            matrix:
                os: [ubuntu-latest,macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: 17
            - name: Execute Gradle build
              run:  ./gradlew test
              env:
                  GE_URL: ${{ secrets.GE_URL }}
                  GE_API_KEY: ${{ secrets.GE_API_KEY }}
