name: Renovate

on:
    schedule:
        - cron: "0 0 * * *"  # This cron job runs every day at midnight. Adjust the schedule as needed.
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Renovate
              uses: renovatebot/github-action@v42.0.6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
